# This is a YAML file

on: push
jobs: 
    third-job:
      runs-on : ubuntu-latest
      steps : 
            - run : node --version
            - run : npm  --version
            - uses : actions/checkout@v4
            - run : npm cli
            - run : npx eslint .
            - run : node xyz.js
            - run : node index.js
            - run : node script.js
